dependencies {
    implementation project(':core')
    implementation libs.spring.boot.starter.web
    implementation libs.bundles.persistence
    testImplementation testFixtures(project(':core'))
}

def ciToken = System.getenv('CI_TOKEN')
def nexusUser = project.findProperty('nexusUser') ?: 'anonymous'

dependencies {
    implementation projects.core
    implementation projects.core.dataTest
}
