<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>bench</groupId><artifactId>wala-driver</artifactId><version>1</version>
  <dependencies>
    <dependency><groupId>com.ibm.wala</groupId><artifactId>com.ibm.wala.core</artifactId><version>1.6.7</version></dependency>
  </dependencies>
</project>
