import dflt, { named, arrowExp, Widget, Klass, registry, takesCb, returnsWidget, documented, typedLet, Proto, wid } from './shapes.js';
import * as ns from './shapes.js';
export function useAll() {
  named(1);
  arrowExp(2);
  dflt();
  ns.named(3);
  ns.default();
  const w = new Widget();
  w.inc();
  w.inc().dec();
  w.handler();
  Widget.create().inc();
  new Klass().run();
  registry.start();
  registry.nested.deep();
  takesCb(named);
  takesCb((n) => named(n));
  takesCb(function () { return named(0); });
  returnsWidget().inc();
  documented().inc();
  typedLet.inc();
  const p = new Proto();
  p.alpha();
  p.beta();
  p.gamma();
  wid.inc();
  let w2;
  w2 = new Widget();
  w2.inc();
  const w3 = returnsWidget();
  w3.dec();
  [w, w2].map((x) => x.inc());
  const chained = new Widget().inc().inc();
  chained.dec();
  useAll();
  const g = w.value;
  w.value;
  return g;
}
