package torture;

// f07 — RECORDS, SEALED HIERARCHIES, PATTERN SWITCH, ENUM CONSTANT BODIES. Language forms whose
// dispatch is decided by the compiler rather than written by hand.

public class F07Modern {

    sealed interface Node permits Leaf, Pair, Empty { }
    record Leaf(String value) implements Node { String render() { return value; } }
    record Pair(Node left, Node right) implements Node { String render() { return "pair"; } }
    static final class Empty implements Node { String render() { return ""; } }

    // PATTERN SWITCH over a sealed hierarchy: exhaustive, and each arm's receiver is narrowed
    String describe(Node n) {
        return switch (n) {
            case Leaf l -> l.render();
            case Pair p -> p.render();
            case Empty e -> e.render();
        };
    }
    // record accessor, generated by the compiler, with no source body
    String accessor(Leaf l) { return l.value(); }
    // a record's own declared method
    String declared(Leaf l) { return l.render(); }
    // nested pattern: the receiver of the inner call is bound by the pattern
    String nested(Node n) {
        if (n instanceof Pair(Leaf a, Node ignored)) return a.render();
        return "";
    }
    // instanceof pattern binding, then a call on the bound name
    String viaInstanceof(Node n) { if (n instanceof Leaf l) return l.render(); return ""; }

    // ENUM with constant bodies: each constant is an anonymous subclass overriding apply
    enum Op {
        ADD { int apply(int a, int b) { return a + b; } },
        MUL { int apply(int a, int b) { return a * b; } };
        abstract int apply(int a, int b);
        int twice(int a) { return apply(a, a); }          // dispatch to the constant body
    }
    int viaEnumAbstract(Op op) { return op.apply(1, 2); }
    int viaEnumInherited(Op op) { return op.twice(3); }
    int viaEnumConstant() { return Op.ADD.apply(1, 2); }

    // switch on a string, and on an enum
    String onString(String k) { return switch (k) { case "a" -> "A"; default -> "?"; }; }
    int onEnum(Op op) { return switch (op) { case ADD -> 1; case MUL -> 2; }; }
}
