// Sized COMFORTABLY OVER the limit -- the everyday throw case.
//
// THE LIMIT IS EXACTLY 32,767 CHARACTERS, AND THAT IS NOW MEASURED.
//
// cs-oracle bracketed it: largest direct parse 32,712, first failure 32,783.
// A binary search against the patched grammar closes the bracket -- 32,767
// parses, 32,768 throws -- so the constant is the measured boundary and not
// the plausible power of two it happens to equal.
//
// It counts CHARACTERS, not bytes, and that is measured too: a 32,767-character
// source containing 1,000 non-ASCII characters is 33,767 BYTES and still
// parses, and one more CHARACTER throws whatever the byte count. A limit check
// written against byte length is wrong in the unsafe direction for any file
// with a non-ASCII comment, and every real codebase has those.
//
// THE FOUR FILES IN THIS PROJECT, THE UNIT, AND THE MARGIN EACH HAS:
//
//   JustUnderTheLine.cs   32,587 characters   parses    180 chars of slack
//   AtTheLimit.cs         32,767 characters   parses      0 -- exact, load-bearing
//   OneOverTheLimit.cs    32,768 characters   THROWS      0 -- exact, load-bearing
//   JustOverTheLine.cs    33,400 characters   THROWS    633 chars of slack
//
// UNIT: CHARACTERS. The generator counted `len(str)` in Python -- code points,
// not bytes -- and ASSERTED every file is pure ASCII so the two coincide. That
// assertion is load-bearing, not tidiness: a must-fail file generated by BYTE
// count cannot fail. 32,768 bytes containing a single non-ASCII character is
// fewer than 32,768 characters, so it parses, the assertion never fires, and
// the gate passes silently. Anyone regenerating these must count characters
// and must keep them ASCII, or must re-verify against the parser.
//
// The middle two are the off-by-one probe and their sizes are load-bearing TO
// THE CHARACTER: they are what distinguishes "the limit is 32,767" from "the
// limit is somewhere around 32,700". The outer two are the everyday pair and
// have slack on purpose, because a fixture that lands near a threshold is a
// fixture whose verdict can flip without anyone noticing they flipped it --
// and `JustOverTheLine.cs` used to sit 88 characters over, which is a line and
// a half of comment.
//
// A gate asserting these four lengths is requested of cs-impl in
// requests-impl.jsonl. Until it exists, the sizes are asserted here and in
// ../MANIFEST.md and nowhere that runs.
//
// ROLE: the everyday throw case, with 633 characters of slack so that ordinary
// editing cannot silently turn it into a file that parses.
using System;

namespace Fixtures.LargeFile;

/// <summary>Sized COMFORTABLY OVER the limit -- the everyday throw case.</summary>
public static class JustOverTheLine
{
    /// <summary>Entry 0000 of the padding catalogue.</summary>
    public static string Entry0000(int value) => $"entry-0000:{value}";

    /// <summary>Entry 0001 of the padding catalogue.</summary>
    public static string Entry0001(int value) => $"entry-0001:{value}";

    /// <summary>Entry 0002 of the padding catalogue.</summary>
    public static string Entry0002(int value) => $"entry-0002:{value}";

    /// <summary>Entry 0003 of the padding catalogue.</summary>
    public static string Entry0003(int value) => $"entry-0003:{value}";

    /// <summary>Entry 0004 of the padding catalogue.</summary>
    public static string Entry0004(int value) => $"entry-0004:{value}";

    /// <summary>Entry 0005 of the padding catalogue.</summary>
    public static string Entry0005(int value) => $"entry-0005:{value}";

    /// <summary>Entry 0006 of the padding catalogue.</summary>
    public static string Entry0006(int value) => $"entry-0006:{value}";

    /// <summary>Entry 0007 of the padding catalogue.</summary>
    public static string Entry0007(int value) => $"entry-0007:{value}";

    /// <summary>Entry 0008 of the padding catalogue.</summary>
    public static string Entry0008(int value) => $"entry-0008:{value}";

    /// <summary>Entry 0009 of the padding catalogue.</summary>
    public static string Entry0009(int value) => $"entry-0009:{value}";

    /// <summary>Entry 0010 of the padding catalogue.</summary>
    public static string Entry0010(int value) => $"entry-0010:{value}";

    /// <summary>Entry 0011 of the padding catalogue.</summary>
    public static string Entry0011(int value) => $"entry-0011:{value}";

    /// <summary>Entry 0012 of the padding catalogue.</summary>
    public static string Entry0012(int value) => $"entry-0012:{value}";

    /// <summary>Entry 0013 of the padding catalogue.</summary>
    public static string Entry0013(int value) => $"entry-0013:{value}";

    /// <summary>Entry 0014 of the padding catalogue.</summary>
    public static string Entry0014(int value) => $"entry-0014:{value}";

    /// <summary>Entry 0015 of the padding catalogue.</summary>
    public static string Entry0015(int value) => $"entry-0015:{value}";

    /// <summary>Entry 0016 of the padding catalogue.</summary>
    public static string Entry0016(int value) => $"entry-0016:{value}";

    /// <summary>Entry 0017 of the padding catalogue.</summary>
    public static string Entry0017(int value) => $"entry-0017:{value}";

    /// <summary>Entry 0018 of the padding catalogue.</summary>
    public static string Entry0018(int value) => $"entry-0018:{value}";

    /// <summary>Entry 0019 of the padding catalogue.</summary>
    public static string Entry0019(int value) => $"entry-0019:{value}";

    /// <summary>Entry 0020 of the padding catalogue.</summary>
    public static string Entry0020(int value) => $"entry-0020:{value}";

    /// <summary>Entry 0021 of the padding catalogue.</summary>
    public static string Entry0021(int value) => $"entry-0021:{value}";

    /// <summary>Entry 0022 of the padding catalogue.</summary>
    public static string Entry0022(int value) => $"entry-0022:{value}";

    /// <summary>Entry 0023 of the padding catalogue.</summary>
    public static string Entry0023(int value) => $"entry-0023:{value}";

    /// <summary>Entry 0024 of the padding catalogue.</summary>
    public static string Entry0024(int value) => $"entry-0024:{value}";

    /// <summary>Entry 0025 of the padding catalogue.</summary>
    public static string Entry0025(int value) => $"entry-0025:{value}";

    /// <summary>Entry 0026 of the padding catalogue.</summary>
    public static string Entry0026(int value) => $"entry-0026:{value}";

    /// <summary>Entry 0027 of the padding catalogue.</summary>
    public static string Entry0027(int value) => $"entry-0027:{value}";

    /// <summary>Entry 0028 of the padding catalogue.</summary>
    public static string Entry0028(int value) => $"entry-0028:{value}";

    /// <summary>Entry 0029 of the padding catalogue.</summary>
    public static string Entry0029(int value) => $"entry-0029:{value}";

    /// <summary>Entry 0030 of the padding catalogue.</summary>
    public static string Entry0030(int value) => $"entry-0030:{value}";

    /// <summary>Entry 0031 of the padding catalogue.</summary>
    public static string Entry0031(int value) => $"entry-0031:{value}";

    /// <summary>Entry 0032 of the padding catalogue.</summary>
    public static string Entry0032(int value) => $"entry-0032:{value}";

    /// <summary>Entry 0033 of the padding catalogue.</summary>
    public static string Entry0033(int value) => $"entry-0033:{value}";

    /// <summary>Entry 0034 of the padding catalogue.</summary>
    public static string Entry0034(int value) => $"entry-0034:{value}";

    /// <summary>Entry 0035 of the padding catalogue.</summary>
    public static string Entry0035(int value) => $"entry-0035:{value}";

    /// <summary>Entry 0036 of the padding catalogue.</summary>
    public static string Entry0036(int value) => $"entry-0036:{value}";

    /// <summary>Entry 0037 of the padding catalogue.</summary>
    public static string Entry0037(int value) => $"entry-0037:{value}";

    /// <summary>Entry 0038 of the padding catalogue.</summary>
    public static string Entry0038(int value) => $"entry-0038:{value}";

    /// <summary>Entry 0039 of the padding catalogue.</summary>
    public static string Entry0039(int value) => $"entry-0039:{value}";

    /// <summary>Entry 0040 of the padding catalogue.</summary>
    public static string Entry0040(int value) => $"entry-0040:{value}";

    /// <summary>Entry 0041 of the padding catalogue.</summary>
    public static string Entry0041(int value) => $"entry-0041:{value}";

    /// <summary>Entry 0042 of the padding catalogue.</summary>
    public static string Entry0042(int value) => $"entry-0042:{value}";

    /// <summary>Entry 0043 of the padding catalogue.</summary>
    public static string Entry0043(int value) => $"entry-0043:{value}";

    /// <summary>Entry 0044 of the padding catalogue.</summary>
    public static string Entry0044(int value) => $"entry-0044:{value}";

    /// <summary>Entry 0045 of the padding catalogue.</summary>
    public static string Entry0045(int value) => $"entry-0045:{value}";

    /// <summary>Entry 0046 of the padding catalogue.</summary>
    public static string Entry0046(int value) => $"entry-0046:{value}";

    /// <summary>Entry 0047 of the padding catalogue.</summary>
    public static string Entry0047(int value) => $"entry-0047:{value}";

    /// <summary>Entry 0048 of the padding catalogue.</summary>
    public static string Entry0048(int value) => $"entry-0048:{value}";

    /// <summary>Entry 0049 of the padding catalogue.</summary>
    public static string Entry0049(int value) => $"entry-0049:{value}";

    /// <summary>Entry 0050 of the padding catalogue.</summary>
    public static string Entry0050(int value) => $"entry-0050:{value}";

    /// <summary>Entry 0051 of the padding catalogue.</summary>
    public static string Entry0051(int value) => $"entry-0051:{value}";

    /// <summary>Entry 0052 of the padding catalogue.</summary>
    public static string Entry0052(int value) => $"entry-0052:{value}";

    /// <summary>Entry 0053 of the padding catalogue.</summary>
    public static string Entry0053(int value) => $"entry-0053:{value}";

    /// <summary>Entry 0054 of the padding catalogue.</summary>
    public static string Entry0054(int value) => $"entry-0054:{value}";

    /// <summary>Entry 0055 of the padding catalogue.</summary>
    public static string Entry0055(int value) => $"entry-0055:{value}";

    /// <summary>Entry 0056 of the padding catalogue.</summary>
    public static string Entry0056(int value) => $"entry-0056:{value}";

    /// <summary>Entry 0057 of the padding catalogue.</summary>
    public static string Entry0057(int value) => $"entry-0057:{value}";

    /// <summary>Entry 0058 of the padding catalogue.</summary>
    public static string Entry0058(int value) => $"entry-0058:{value}";

    /// <summary>Entry 0059 of the padding catalogue.</summary>
    public static string Entry0059(int value) => $"entry-0059:{value}";

    /// <summary>Entry 0060 of the padding catalogue.</summary>
    public static string Entry0060(int value) => $"entry-0060:{value}";

    /// <summary>Entry 0061 of the padding catalogue.</summary>
    public static string Entry0061(int value) => $"entry-0061:{value}";

    /// <summary>Entry 0062 of the padding catalogue.</summary>
    public static string Entry0062(int value) => $"entry-0062:{value}";

    /// <summary>Entry 0063 of the padding catalogue.</summary>
    public static string Entry0063(int value) => $"entry-0063:{value}";

    /// <summary>Entry 0064 of the padding catalogue.</summary>
    public static string Entry0064(int value) => $"entry-0064:{value}";

    /// <summary>Entry 0065 of the padding catalogue.</summary>
    public static string Entry0065(int value) => $"entry-0065:{value}";

    /// <summary>Entry 0066 of the padding catalogue.</summary>
    public static string Entry0066(int value) => $"entry-0066:{value}";

    /// <summary>Entry 0067 of the padding catalogue.</summary>
    public static string Entry0067(int value) => $"entry-0067:{value}";

    /// <summary>Entry 0068 of the padding catalogue.</summary>
    public static string Entry0068(int value) => $"entry-0068:{value}";

    /// <summary>Entry 0069 of the padding catalogue.</summary>
    public static string Entry0069(int value) => $"entry-0069:{value}";

    /// <summary>Entry 0070 of the padding catalogue.</summary>
    public static string Entry0070(int value) => $"entry-0070:{value}";

    /// <summary>Entry 0071 of the padding catalogue.</summary>
    public static string Entry0071(int value) => $"entry-0071:{value}";

    /// <summary>Entry 0072 of the padding catalogue.</summary>
    public static string Entry0072(int value) => $"entry-0072:{value}";

    /// <summary>Entry 0073 of the padding catalogue.</summary>
    public static string Entry0073(int value) => $"entry-0073:{value}";

    /// <summary>Entry 0074 of the padding catalogue.</summary>
    public static string Entry0074(int value) => $"entry-0074:{value}";

    /// <summary>Entry 0075 of the padding catalogue.</summary>
    public static string Entry0075(int value) => $"entry-0075:{value}";

    /// <summary>Entry 0076 of the padding catalogue.</summary>
    public static string Entry0076(int value) => $"entry-0076:{value}";

    /// <summary>Entry 0077 of the padding catalogue.</summary>
    public static string Entry0077(int value) => $"entry-0077:{value}";

    /// <summary>Entry 0078 of the padding catalogue.</summary>
    public static string Entry0078(int value) => $"entry-0078:{value}";

    /// <summary>Entry 0079 of the padding catalogue.</summary>
    public static string Entry0079(int value) => $"entry-0079:{value}";

    /// <summary>Entry 0080 of the padding catalogue.</summary>
    public static string Entry0080(int value) => $"entry-0080:{value}";

    /// <summary>Entry 0081 of the padding catalogue.</summary>
    public static string Entry0081(int value) => $"entry-0081:{value}";

    /// <summary>Entry 0082 of the padding catalogue.</summary>
    public static string Entry0082(int value) => $"entry-0082:{value}";

    /// <summary>Entry 0083 of the padding catalogue.</summary>
    public static string Entry0083(int value) => $"entry-0083:{value}";

    /// <summary>Entry 0084 of the padding catalogue.</summary>
    public static string Entry0084(int value) => $"entry-0084:{value}";

    /// <summary>Entry 0085 of the padding catalogue.</summary>
    public static string Entry0085(int value) => $"entry-0085:{value}";

    /// <summary>Entry 0086 of the padding catalogue.</summary>
    public static string Entry0086(int value) => $"entry-0086:{value}";

    /// <summary>Entry 0087 of the padding catalogue.</summary>
    public static string Entry0087(int value) => $"entry-0087:{value}";

    /// <summary>Entry 0088 of the padding catalogue.</summary>
    public static string Entry0088(int value) => $"entry-0088:{value}";

    /// <summary>Entry 0089 of the padding catalogue.</summary>
    public static string Entry0089(int value) => $"entry-0089:{value}";

    /// <summary>Entry 0090 of the padding catalogue.</summary>
    public static string Entry0090(int value) => $"entry-0090:{value}";

    /// <summary>Entry 0091 of the padding catalogue.</summary>
    public static string Entry0091(int value) => $"entry-0091:{value}";

    /// <summary>Entry 0092 of the padding catalogue.</summary>
    public static string Entry0092(int value) => $"entry-0092:{value}";

    /// <summary>Entry 0093 of the padding catalogue.</summary>
    public static string Entry0093(int value) => $"entry-0093:{value}";

    /// <summary>Entry 0094 of the padding catalogue.</summary>
    public static string Entry0094(int value) => $"entry-0094:{value}";

    /// <summary>Entry 0095 of the padding catalogue.</summary>
    public static string Entry0095(int value) => $"entry-0095:{value}";

    /// <summary>Entry 0096 of the padding catalogue.</summary>
    public static string Entry0096(int value) => $"entry-0096:{value}";

    /// <summary>Entry 0097 of the padding catalogue.</summary>
    public static string Entry0097(int value) => $"entry-0097:{value}";

    /// <summary>Entry 0098 of the padding catalogue.</summary>
    public static string Entry0098(int value) => $"entry-0098:{value}";

    /// <summary>Entry 0099 of the padding catalogue.</summary>
    public static string Entry0099(int value) => $"entry-0099:{value}";

    /// <summary>Entry 0100 of the padding catalogue.</summary>
    public static string Entry0100(int value) => $"entry-0100:{value}";

    /// <summary>Entry 0101 of the padding catalogue.</summary>
    public static string Entry0101(int value) => $"entry-0101:{value}";

    /// <summary>Entry 0102 of the padding catalogue.</summary>
    public static string Entry0102(int value) => $"entry-0102:{value}";

    /// <summary>Entry 0103 of the padding catalogue.</summary>
    public static string Entry0103(int value) => $"entry-0103:{value}";

    /// <summary>Entry 0104 of the padding catalogue.</summary>
    public static string Entry0104(int value) => $"entry-0104:{value}";

    /// <summary>Entry 0105 of the padding catalogue.</summary>
    public static string Entry0105(int value) => $"entry-0105:{value}";

    /// <summary>Entry 0106 of the padding catalogue.</summary>
    public static string Entry0106(int value) => $"entry-0106:{value}";

    /// <summary>Entry 0107 of the padding catalogue.</summary>
    public static string Entry0107(int value) => $"entry-0107:{value}";

    /// <summary>Entry 0108 of the padding catalogue.</summary>
    public static string Entry0108(int value) => $"entry-0108:{value}";

    /// <summary>Entry 0109 of the padding catalogue.</summary>
    public static string Entry0109(int value) => $"entry-0109:{value}";

    /// <summary>Entry 0110 of the padding catalogue.</summary>
    public static string Entry0110(int value) => $"entry-0110:{value}";

    /// <summary>Entry 0111 of the padding catalogue.</summary>
    public static string Entry0111(int value) => $"entry-0111:{value}";

    /// <summary>Entry 0112 of the padding catalogue.</summary>
    public static string Entry0112(int value) => $"entry-0112:{value}";

    /// <summary>Entry 0113 of the padding catalogue.</summary>
    public static string Entry0113(int value) => $"entry-0113:{value}";

    /// <summary>Entry 0114 of the padding catalogue.</summary>
    public static string Entry0114(int value) => $"entry-0114:{value}";

    /// <summary>Entry 0115 of the padding catalogue.</summary>
    public static string Entry0115(int value) => $"entry-0115:{value}";

    /// <summary>Entry 0116 of the padding catalogue.</summary>
    public static string Entry0116(int value) => $"entry-0116:{value}";

    /// <summary>Entry 0117 of the padding catalogue.</summary>
    public static string Entry0117(int value) => $"entry-0117:{value}";

    /// <summary>Entry 0118 of the padding catalogue.</summary>
    public static string Entry0118(int value) => $"entry-0118:{value}";

    /// <summary>Entry 0119 of the padding catalogue.</summary>
    public static string Entry0119(int value) => $"entry-0119:{value}";

    /// <summary>Entry 0120 of the padding catalogue.</summary>
    public static string Entry0120(int value) => $"entry-0120:{value}";

    /// <summary>Entry 0121 of the padding catalogue.</summary>
    public static string Entry0121(int value) => $"entry-0121:{value}";

    /// <summary>Entry 0122 of the padding catalogue.</summary>
    public static string Entry0122(int value) => $"entry-0122:{value}";

    /// <summary>Entry 0123 of the padding catalogue.</summary>
    public static string Entry0123(int value) => $"entry-0123:{value}";

    /// <summary>Entry 0124 of the padding catalogue.</summary>
    public static string Entry0124(int value) => $"entry-0124:{value}";

    /// <summary>Entry 0125 of the padding catalogue.</summary>
    public static string Entry0125(int value) => $"entry-0125:{value}";

    /// <summary>Entry 0126 of the padding catalogue.</summary>
    public static string Entry0126(int value) => $"entry-0126:{value}";

    /// <summary>Entry 0127 of the padding catalogue.</summary>
    public static string Entry0127(int value) => $"entry-0127:{value}";

    /// <summary>Entry 0128 of the padding catalogue.</summary>
    public static string Entry0128(int value) => $"entry-0128:{value}";

    /// <summary>Entry 0129 of the padding catalogue.</summary>
    public static string Entry0129(int value) => $"entry-0129:{value}";

    /// <summary>Entry 0130 of the padding catalogue.</summary>
    public static string Entry0130(int value) => $"entry-0130:{value}";

    /// <summary>Entry 0131 of the padding catalogue.</summary>
    public static string Entry0131(int value) => $"entry-0131:{value}";

    /// <summary>Entry 0132 of the padding catalogue.</summary>
    public static string Entry0132(int value) => $"entry-0132:{value}";

    /// <summary>Entry 0133 of the padding catalogue.</summary>
    public static string Entry0133(int value) => $"entry-0133:{value}";

    /// <summary>Entry 0134 of the padding catalogue.</summary>
    public static string Entry0134(int value) => $"entry-0134:{value}";

    /// <summary>Entry 0135 of the padding catalogue.</summary>
    public static string Entry0135(int value) => $"entry-0135:{value}";

    /// <summary>Entry 0136 of the padding catalogue.</summary>
    public static string Entry0136(int value) => $"entry-0136:{value}";

    /// <summary>Entry 0137 of the padding catalogue.</summary>
    public static string Entry0137(int value) => $"entry-0137:{value}";

    /// <summary>Entry 0138 of the padding catalogue.</summary>
    public static string Entry0138(int value) => $"entry-0138:{value}";

    /// <summary>Entry 0139 of the padding catalogue.</summary>
    public static string Entry0139(int value) => $"entry-0139:{value}";

    /// <summary>Entry 0140 of the padding catalogue.</summary>
    public static string Entry0140(int value) => $"entry-0140:{value}";

    /// <summary>Entry 0141 of the padding catalogue.</summary>
    public static string Entry0141(int value) => $"entry-0141:{value}";

    /// <summary>Entry 0142 of the padding catalogue.</summary>
    public static string Entry0142(int value) => $"entry-0142:{value}";

    /// <summary>Entry 0143 of the padding catalogue.</summary>
    public static string Entry0143(int value) => $"entry-0143:{value}";

    /// <summary>Entry 0144 of the padding catalogue.</summary>
    public static string Entry0144(int value) => $"entry-0144:{value}";

    /// <summary>Entry 0145 of the padding catalogue.</summary>
    public static string Entry0145(int value) => $"entry-0145:{value}";

    /// <summary>Entry 0146 of the padding catalogue.</summary>
    public static string Entry0146(int value) => $"entry-0146:{value}";

    /// <summary>Entry 0147 of the padding catalogue.</summary>
    public static string Entry0147(int value) => $"entry-0147:{value}";

    /// <summary>Entry 0148 of the padding catalogue.</summary>
    public static string Entry0148(int value) => $"entry-0148:{value}";

    /// <summary>Entry 0149 of the padding catalogue.</summary>
    public static string Entry0149(int value) => $"entry-0149:{value}";

    /// <summary>Entry 0150 of the padding catalogue.</summary>
    public static string Entry0150(int value) => $"entry-0150:{value}";

    /// <summary>Entry 0151 of the padding catalogue.</summary>
    public static string Entry0151(int value) => $"entry-0151:{value}";

    /// <summary>Entry 0152 of the padding catalogue.</summary>
    public static string Entry0152(int value) => $"entry-0152:{value}";

    /// <summary>Entry 0153 of the padding catalogue.</summary>
    public static string Entry0153(int value) => $"entry-0153:{value}";

    /// <summary>Entry 0154 of the padding catalogue.</summary>
    public static string Entry0154(int value) => $"entry-0154:{value}";

    /// <summary>Entry 0155 of the padding catalogue.</summary>
    public static string Entry0155(int value) => $"entry-0155:{value}";

    /// <summary>Entry 0156 of the padding catalogue.</summary>
    public static string Entry0156(int value) => $"entry-0156:{value}";

    /// <summary>Entry 0157 of the padding catalogue.</summary>
    public static string Entry0157(int value) => $"entry-0157:{value}";

    /// <summary>Entry 0158 of the padding catalogue.</summary>
    public static string Entry0158(int value) => $"entry-0158:{value}";

    /// <summary>Entry 0159 of the padding catalogue.</summary>
    public static string Entry0159(int value) => $"entry-0159:{value}";

    /// <summary>Entry 0160 of the padding catalogue.</summary>
    public static string Entry0160(int value) => $"entry-0160:{value}";

    /// <summary>Entry 0161 of the padding catalogue.</summary>
    public static string Entry0161(int value) => $"entry-0161:{value}";

    /// <summary>Entry 0162 of the padding catalogue.</summary>
    public static string Entry0162(int value) => $"entry-0162:{value}";

    /// <summary>Entry 0163 of the padding catalogue.</summary>
    public static string Entry0163(int value) => $"entry-0163:{value}";

    /// <summary>Entry 0164 of the padding catalogue.</summary>
    public static string Entry0164(int value) => $"entry-0164:{value}";

    /// <summary>Entry 0165 of the padding catalogue.</summary>
    public static string Entry0165(int value) => $"entry-0165:{value}";

    /// <summary>Entry 0166 of the padding catalogue.</summary>
    public static string Entry0166(int value) => $"entry-0166:{value}";

    /// <summary>Entry 0167 of the padding catalogue.</summary>
    public static string Entry0167(int value) => $"entry-0167:{value}";

    /// <summary>Entry 0168 of the padding catalogue.</summary>
    public static string Entry0168(int value) => $"entry-0168:{value}";

    /// <summary>Entry 0169 of the padding catalogue.</summary>
    public static string Entry0169(int value) => $"entry-0169:{value}";

    /// <summary>Entry 0170 of the padding catalogue.</summary>
    public static string Entry0170(int value) => $"entry-0170:{value}";

    /// <summary>Entry 0171 of the padding catalogue.</summary>
    public static string Entry0171(int value) => $"entry-0171:{value}";

    /// <summary>Entry 0172 of the padding catalogue.</summary>
    public static string Entry0172(int value) => $"entry-0172:{value}";

    /// <summary>Entry 0173 of the padding catalogue.</summary>
    public static string Entry0173(int value) => $"entry-0173:{value}";

    /// <summary>Entry 0174 of the padding catalogue.</summary>
    public static string Entry0174(int value) => $"entry-0174:{value}";

    /// <summary>Entry 0175 of the padding catalogue.</summary>
    public static string Entry0175(int value) => $"entry-0175:{value}";

    /// <summary>Entry 0176 of the padding catalogue.</summary>
    public static string Entry0176(int value) => $"entry-0176:{value}";

    /// <summary>Entry 0177 of the padding catalogue.</summary>
    public static string Entry0177(int value) => $"entry-0177:{value}";

    /// <summary>Entry 0178 of the padding catalogue.</summary>
    public static string Entry0178(int value) => $"entry-0178:{value}";

    /// <summary>Entry 0179 of the padding catalogue.</summary>
    public static string Entry0179(int value) => $"entry-0179:{value}";

    /// <summary>Entry 0180 of the padding catalogue.</summary>
    public static string Entry0180(int value) => $"entry-0180:{value}";

    /// <summary>Entry 0181 of the padding catalogue.</summary>
    public static string Entry0181(int value) => $"entry-0181:{value}";

    /// <summary>Entry 0182 of the padding catalogue.</summary>
    public static string Entry0182(int value) => $"entry-0182:{value}";

    /// <summary>Entry 0183 of the padding catalogue.</summary>
    public static string Entry0183(int value) => $"entry-0183:{value}";

    /// <summary>Entry 0184 of the padding catalogue.</summary>
    public static string Entry0184(int value) => $"entry-0184:{value}";

    /// <summary>Entry 0185 of the padding catalogue.</summary>
    public static string Entry0185(int value) => $"entry-0185:{value}";

    /// <summary>Entry 0186 of the padding catalogue.</summary>
    public static string Entry0186(int value) => $"entry-0186:{value}";

    /// <summary>Entry 0187 of the padding catalogue.</summary>
    public static string Entry0187(int value) => $"entry-0187:{value}";

    /// <summary>Entry 0188 of the padding catalogue.</summary>
    public static string Entry0188(int value) => $"entry-0188:{value}";

    /// <summary>Entry 0189 of the padding catalogue.</summary>
    public static string Entry0189(int value) => $"entry-0189:{value}";

    /// <summary>Entry 0190 of the padding catalogue.</summary>
    public static string Entry0190(int value) => $"entry-0190:{value}";

    /// <summary>Entry 0191 of the padding catalogue.</summary>
    public static string Entry0191(int value) => $"entry-0191:{value}";

    /// <summary>Entry 0192 of the padding catalogue.</summary>
    public static string Entry0192(int value) => $"entry-0192:{value}";

    /// <summary>Entry 0193 of the padding catalogue.</summary>
    public static string Entry0193(int value) => $"entry-0193:{value}";

    /// <summary>Entry 0194 of the padding catalogue.</summary>
    public static string Entry0194(int value) => $"entry-0194:{value}";

    /// <summary>Entry 0195 of the padding catalogue.</summary>
    public static string Entry0195(int value) => $"entry-0195:{value}";

    /// <summary>Entry 0196 of the padding catalogue.</summary>
    public static string Entry0196(int value) => $"entry-0196:{value}";

    /// <summary>Entry 0197 of the padding catalogue.</summary>
    public static string Entry0197(int value) => $"entry-0197:{value}";

    /// <summary>Entry 0198 of the padding catalogue.</summary>
    public static string Entry0198(int value) => $"entry-0198:{value}";

    /// <summary>Entry 0199 of the padding catalogue.</summary>
    public static string Entry0199(int value) => $"entry-0199:{value}";

    /// <summary>Entry 0200 of the padding catalogue.</summary>
    public static string Entry0200(int value) => $"entry-0200:{value}";

    /// <summary>Entry 0201 of the padding catalogue.</summary>
    public static string Entry0201(int value) => $"entry-0201:{value}";

    /// <summary>Entry 0202 of the padding catalogue.</summary>
    public static string Entry0202(int value) => $"entry-0202:{value}";

    /// <summary>Entry 0203 of the padding catalogue.</summary>
    public static string Entry0203(int value) => $"entry-0203:{value}";

    /// <summary>Entry 0204 of the padding catalogue.</summary>
    public static string Entry0204(int value) => $"entry-0204:{value}";

    /// <summary>Entry 0205 of the padding catalogue.</summary>
    public static string Entry0205(int value) => $"entry-0205:{value}";

    /// <summary>Entry 0206 of the padding catalogue.</summary>
    public static string Entry0206(int value) => $"entry-0206:{value}";

    /// <summary>Entry 0207 of the padding catalogue.</summary>
    public static string Entry0207(int value) => $"entry-0207:{value}";

    /// <summary>Entry 0208 of the padding catalogue.</summary>
    public static string Entry0208(int value) => $"entry-0208:{value}";

    /// <summary>Entry 0209 of the padding catalogue.</summary>
    public static string Entry0209(int value) => $"entry-0209:{value}";

    /// <summary>Entry 0210 of the padding catalogue.</summary>
    public static string Entry0210(int value) => $"entry-0210:{value}";

    /// <summary>Entry 0211 of the padding catalogue.</summary>
    public static string Entry0211(int value) => $"entry-0211:{value}";

    /// <summary>Entry 0212 of the padding catalogue.</summary>
    public static string Entry0212(int value) => $"entry-0212:{value}";

    /// <summary>Entry 0213 of the padding catalogue.</summary>
    public static string Entry0213(int value) => $"entry-0213:{value}";

    /// <summary>Entry 0214 of the padding catalogue.</summary>
    public static string Entry0214(int value) => $"entry-0214:{value}";

    /// <summary>Entry 0215 of the padding catalogue.</summary>
    public static string Entry0215(int value) => $"entry-0215:{value}";

    /// <summary>Entry 0216 of the padding catalogue.</summary>
    public static string Entry0216(int value) => $"entry-0216:{value}";

    /// <summary>Entry 0217 of the padding catalogue.</summary>
    public static string Entry0217(int value) => $"entry-0217:{value}";

    /// <summary>Entry 0218 of the padding catalogue.</summary>
    public static string Entry0218(int value) => $"entry-0218:{value}";

    /// <summary>Entry 0219 of the padding catalogue.</summary>
    public static string Entry0219(int value) => $"entry-0219:{value}";

    /// <summary>Entry 0220 of the padding catalogue.</summary>
    public static string Entry0220(int value) => $"entry-0220:{value}";

    /// <summary>Entry 0221 of the padding catalogue.</summary>
    public static string Entry0221(int value) => $"entry-0221:{value}";

    /// <summary>The last member. Its presence is the measurement.</summary>
    public static string LastMemberOver() => "LastMemberOver";
}
// ...............................................................................................................
