// HALF TWO — no Java analogue.
//
// A delegate is a NAMED TYPE whose values are method references. Java's nearest
// thing is a functional interface, which is structurally different: Java infers
// the target from an interface with one abstract method, C# declares a type
// whose whole content is a signature. The schema gives it TypeCategory.DELEGATE
// and fills the `methodReferenceKind` slot that TypeScript documents as
// permanently empty.
//
// The construct that matters most for the call graph is METHOD GROUP
// CONVERSION, in MethodGroups.cs: `X = M;` is a reference to a method with NO
// CALL SYNTAX ANYWHERE.
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Fixtures.CSharpOnly.Delegates;

// Declaration forms: void, returning, generic, variant, nested, with default
// and params parameters, and with ref/out.
public delegate void Notify();

public delegate void NotifyWith(string message);

public delegate int Transform(int input);

public delegate TOut Project<TIn, TOut>(TIn input);

public delegate TOut Variant<in TIn, out TOut>(TIn input);

public delegate bool TryConvert<TIn, TOut>(TIn input, out TOut result);

public delegate void ByReference(ref int value);

public delegate void WithDefault(int value = 1);

public delegate int WithParams(params int[] values);

public delegate ref int RefReturning(int[] data);

public delegate Task<int> AsyncReturning(int input);

public class DelegateHost
{
    // A delegate type NESTED in a class.
    public delegate void Nested(int value);

    // Delegate-typed fields, properties, parameters, returns and locals.
    public Transform Field = x => x;

    public Transform Property { get; set; } = x => x;

    public Func<int, int> BclField = x => x;

    public Action<string> BclAction = s => { };

    public Predicate<int> BclPredicate = x => x > 0;

    public Comparison<int> BclComparison = (a, b) => a - b;

    public EventHandler BclEventHandler = (s, e) => { };

    public Func<int, int, int, int, int> FourArity = (a, b, c, d) => a + b + c + d;

    public Action<int, int, int, int, int> FiveArityAction = (a, b, c, d, e) => { };

    public Func<Task<int>> AsyncFunc = () => Task.FromResult(1);

    public Transform Returns() => Field;

    public void Accepts(Transform transform, Func<int, int> func, Action action)
    {
    }

    // Construction, invocation and combination.
    public int InstanceMethod(int value) => value + 1;

    public static int StaticMethod(int value) => value + 2;

    public void ConstructionForms()
    {
        // Explicit delegate creation from an instance method group.
        Transform fromInstance = new Transform(InstanceMethod);

        // From a static method group.
        Transform fromStatic = new Transform(StaticMethod);

        // From a lambda and from an anonymous method.
        Transform fromLambda = new Transform(x => x);
        Transform fromAnonymous = new Transform(delegate (int x) { return x; });

        // From another delegate of the same shape but a different TYPE:
        // delegates are nominal, so this needs an explicit conversion through
        // a method group or a lambda, not an assignment.
        Func<int, int> asFunc = fromInstance.Invoke;
        Transform back = new Transform(asFunc);

        // Invocation: the two spellings are the same call.
        _ = fromInstance(1);
        _ = fromInstance.Invoke(1);
        _ = fromStatic(2);
        _ = fromLambda(3);
        _ = fromAnonymous(4);
        _ = back(5);

        // Null-conditional invocation, which is the safe-raise idiom.
        Transform? maybe = null;
        _ = maybe?.Invoke(1);

        // Multicast: combination, removal, and the operators that do it.
        Notify a = () => Console.WriteLine("a");
        Notify b = () => Console.WriteLine("b");
        Notify both = a + b;
        both += a;
        both -= b;
        Notify? combined = (Notify?)Delegate.Combine(a, b);
        Notify? removed = (Notify?)Delegate.Remove(both, a);
        both?.Invoke();
        combined?.Invoke();
        removed?.Invoke();

        // The invocation list of a multicast delegate — the reflective view of
        // the same edge.
        foreach (Delegate d in both!.GetInvocationList())
        {
            _ = d.Method.Name;
            _ = d.Target;
        }
    }

    // ANONYMOUS METHODS — the C# 2 spelling, still legal, still generated by
    // tooling. Three sub-forms: with a parameter list, with NO parameter list
    // at all (which matches any signature), and with a body that captures.
    public void AnonymousMethods()
    {
        Transform withParameters = delegate (int x) { return x + 1; };

        // No parameter list: legal for any delegate type whose parameters are
        // not `out`. There is no lambda equivalent of this.
        Notify noParameterList = delegate { Console.WriteLine(); };
        NotifyWith alsoNoParameterList = delegate { Console.WriteLine(); };
        EventHandler handlerNoParameters = delegate { };

        int captured = 1;
        Transform capturing = delegate (int x) { return x + captured; };

        // Anonymous method in argument position.
        Apply(delegate (int x) { return x * 2; });

        _ = withParameters(1) + capturing(1);
        noParameterList();
        alsoNoParameterList("s");
        handlerNoParameters(this, EventArgs.Empty);
    }

    private static int Apply(Transform transform) => transform(1);

    // A delegate with `ref`/`out` parameters — the signature must match
    // exactly, modifiers included.
    public void RefAndOutDelegates()
    {
        ByReference increment = (ref int v) => v++;
        int value = 1;
        increment(ref value);

        TryConvert<string, int> parse = (string s, out int r) => int.TryParse(s, out r);
        if (parse("42", out int parsed))
        {
            _ = parsed;
        }

        // A method group with matching ref/out modifiers.
        TryConvert<string, int> fromGroup = int.TryParse;
        _ = fromGroup("7", out int alsoParsed) ? alsoParsed : 0;

        _ = value;
    }

    // Variance in action: a delegate value of one constructed type assigned to
    // a variable of another, legal only because of `in`/`out`.
    public void Variance()
    {
        Variant<object, string> source = o => o?.ToString() ?? string.Empty;
        Variant<string, object> widened = source;
        _ = widened("s");

        Func<string> covariant = () => "s";
        Func<object> asObject = covariant;
        _ = asObject();

        Action<object> contravariant = o => { };
        Action<string> asString = contravariant;
        asString("s");
    }

    // Delegates in collections, as dictionary values and as type arguments —
    // the shape a command dispatcher takes, where every call edge in the
    // program goes through one `Invoke`.
    public static readonly Dictionary<string, Func<int, int>> Dispatch = new()
    {
        ["inc"] = x => x + 1,
        ["dec"] = x => x - 1,
        ["neg"] = Negate
    };

    private static int Negate(int value) => -value;

    public static int Run(string command, int value) => Dispatch[command](value);

    public static int RunIndirect(string command, int value) => Dispatch[command].Invoke(value);
}
