#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# A COMPILER-GENERATED CALLEE IS NOT A CALL THE SOURCE MAKES.
#
# ClassFileOracle skips a synthetic or bridge method when it is the CALLER, by access flag. On the
# CALLEE side it used to skip only by NAME, against `$values`, `values`, `valueOf`,
# `$deserializeLambda$` and `access$*` -- javac's vocabulary. A member generated by a different
# compiler was therefore emitted as ground truth, and the engine was scored MISSING for an edge
# whose call does not appear in the source. Measured at 94 such edges on one Eclipse-compiled
# project, 11% of its entire recall gap. See issue #199.
#
# Every synthetic member javac emits is already on that name list, which is exactly why the gap
# was invisible -- so this asserts the flag path directly, by setting ACC_SYNTHETIC on an ordinary
# method (tools/set_method_flag.py) rather than by requiring a second compiler to be installed.
# ─────────────────────────────────────────────────────────────────────────────
set -uo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
W="$(mktemp -d)"; trap 'rm -rf "$W"' EXIT

command -v javac >/dev/null 2>&1 || { echo "synthetic-callee: SKIP (no javac)"; exit 0; }
mkdir -p "$W/src/p" "$W/cls" "$W/oc"
. "$HERE/oracle-build.sh"
ORACLE_FLAGS="$(oracle_build "$W/oc" "$W/oc.log")" \
  || { echo "synthetic-callee: SKIP (ClassFileOracle does not compile on this JDK, see $W/oc.log)"; exit 0; }

cat > "$W/src/p/Probe.java" <<'EOF'
package p;
public class Probe {
    static int helper() { return 1; }      // stands in for a compiler-generated member
    static int plain()  { return 2; }      // an ordinary method, the control
    int useHelper() { return helper(); }
    int usePlain()  { return plain(); }
}
EOF
javac -g -d "$W/cls" "$W/src/p/Probe.java" || { echo "  FAIL (javac)"; exit 1; }

oracle(){ java $ORACLE_FLAGS -cp "$W/oc" ClassFileOracle --app "$W/cls" --app-only 2>/dev/null | grep -- '->' || true; }

# Quiet on success -- this runs as a preflight before every suite run, and four green lines that
# are always green is noise. SYNTHETIC_CALLEE_VERBOSE=1 shows each check.
fail=0
ok(){ [ -n "${SYNTHETIC_CALLEE_VERBOSE:-}" ] && printf '  ok    %s\n' "$1"; return 0; }
before="$(oracle)"
echo "$before" | grep -q 'useHelper() -> p.Probe#helper()' \
  && ok "a plain callee is ground truth before the flag is set" \
  || { echo "  FAIL  expected an edge to helper() before flagging; got:"; echo "$before" | sed 's/^/          /'; fail=1; }

python3 "$HERE/set_method_flag.py" "$W/cls/p/Probe.class" helper 0x1000 >/dev/null \
  || { echo "  FAIL  could not set ACC_SYNTHETIC"; exit 1; }

after="$(oracle)"
if echo "$after" | grep -q '\-> p.Probe#helper()'; then
  echo "  FAIL  a callee declared ACC_SYNTHETIC is still emitted as a must-have edge:"
  echo "$after" | grep '\-> p.Probe#helper()' | sed 's/^/          /'
  fail=1
else
  ok "a callee declared ACC_SYNTHETIC is not emitted"
fi

# The exclusion must be the FLAG, not "drop anything from this class": the control edge stays.
echo "$after" | grep -q 'usePlain() -> p.Probe#plain()' \
  && ok "an ordinary callee in the same class is unaffected" \
  || { echo "  FAIL  the control edge to plain() was lost too:"; echo "$after" | sed 's/^/          /'; fail=1; }

# ACC_BRIDGE takes the same path, and is what a generic override compiles to.
javac -g -d "$W/cls" "$W/src/p/Probe.java" >/dev/null 2>&1
python3 "$HERE/set_method_flag.py" "$W/cls/p/Probe.class" helper 0x0040 >/dev/null
echo "$(oracle)" | grep -q '\-> p.Probe#helper()' \
  && { echo "  FAIL  a callee declared ACC_BRIDGE is still emitted"; fail=1; } \
  || ok "a callee declared ACC_BRIDGE is not emitted"

# ── A COVARIANT-RETURN OVERRIDE SHARES ITS KEY WITH THE BRIDGE BESIDE IT ─────────────────
# The oracle keys a method by (name, params) with NO return type. `protected Base copy()`
# overridden as `protected Sub copy()` makes javac emit a bridge `copy()->Base` on Sub AND a
# bridge `copy()->Object`-shaped twin on each level, so the SAME key names both a real method and
# a synthetic one. Excluding on the flag alone therefore made the REAL method unreachable and
# dropped a written `super.copy()` call -- which is a wrong number in the other direction, the
# exact failure this whole exclusion exists to prevent.
#
# This is not hypothetical: it is what 34-object-members' `super.clone()` edge does, and the first
# version of this fix lost it. No flag patching here -- javac generates the bridge itself.
mkdir -p "$W/src2/p" "$W/cls2"
# The collision has to be on the CALLEE's declaring class, which is what makes this subtle: a
# covariant override alone puts the bridge on the SUBclass. Base has to implement a GENERIC
# supertype at its own type, so javac emits `make()->Object` as a bridge on BASE, beside Base's
# real `make()->Base`. Both then share the key `make()`, and the written `super.make()` call names
# the real one. (34-object-members hits the same shape through Cloneable and Object.clone.)
cat > "$W/src2/p/Cov.java" <<'EOF'
package p;
public class Cov {
    interface Maker<T> { T make(); }
    static class Base implements Maker<Base> { public Base make() { return this; } }
    static class Sub extends Base {
        @Override public Sub make() { Base b = super.make(); return (Sub) b; }
    }
}
EOF
javac -g -d "$W/cls2" "$W/src2/p/Cov.java" || { echo "  FAIL (javac, covariant fixture)"; exit 1; }
cov="$(java $ORACLE_FLAGS -cp "$W/oc" ClassFileOracle --app "$W/cls2" --app-only 2>/dev/null | grep -- '->' || true)"
echo "$cov" | grep -q 'p.Cov.Sub#make() -> p.Cov.Base#make()'   && ok "a real method sharing its key with a bridge is still ground truth"   || { echo "  FAIL  the covariant override's super.make() edge was dropped as synthetic:";
       echo "${cov:-(no edges at all)}" | sed 's/^/          /'; fail=1; }

[ "$fail" = 0 ] && echo "synthetic-callee: ok" || echo "synthetic-callee: FAILED"
exit "$fail"
